### ISSUE TITLE
Can we have 64-bit long mode support please?

### ISSUE THREAD

**Issue by akalsi87** [fwsGonzo/barebones#1]

**Comment by fwsGonzo** [comment]
I will add it once I`m "done" with my GBC emulator project. So I`ll add this feature during christmas at the latest.

**Comment by fwsGonzo** [comment]
Alright, its a bit late, but the kernel is 64-bit now. I added a tag for the 32-bit variant so that it's possible to go back. There has to be a chainloader now that is a 32-bit kernel that loads the 64-bit kernel as a multiboot module for qemu to accept the 64-bit ELF. It's really a Qemu issue, as GRUB has no problem accepting 64-bit multiboot ELFs.

**Comment by akalsi87** [comment]
Thanks!
